apiVersion: apps/v1
kind: Deployment
metadata:
  name: valaxy-deployment
spec:
  selector:
    matchLabels:
      app: valaxy-devops-project
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:1
      maxUnavalable:1
      
  template:
    metadata:
      labels:
        app: valaxy-devops-project
    spec:
      containers:
      - name: valaxy-devops-project
        image: grldev/simple-devops-image
        imagePullPolicy: Always
        ports:
          ContainerPort:8080
